all: printf_arit_variablen printf_arit
printf_arit: printf_arit.c
	gcc -o printf_arit printf_arit.c

printf_arit_variablen: printf_arit_variablen.c
	gcc -o printf_arit_variablen printf_arit_variablen.c
